language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
scripts:
  - yarn test
notifications:
  slack: laboratorioplatzi:hLwWi7KlucuNBjy7w11a8BmV
  email:
  recipients:
    - mariocastro.pva@gmail.com
    - mariocastro.dev@gmail.com
  on_success: always
  on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 5d83f0ba-bc5a-4831-b7ed-52e868ed8c5e
  app: platzi-store-backend-mario
  on:
    repo: bigmario/platzi-store-backend